"""reconcile model drift: JSONB, NOT NULL, unique indexes

Revision ID: 0ac5d8e333f6
Revises: 013
Create Date: 2026-08-09 00:00:09.791482
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0ac5d8e333f6"
down_revision: str | None = "013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "idempotency_keys",
        "response_json",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "idempotency_keys",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "llm_usage",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("merchants_hashed_api_key_key"), "merchants", type_="unique")
    op.drop_index(op.f("ix_merchants_hashed_api_key"), table_name="merchants")
    op.create_index(op.f("ix_merchants_hashed_api_key"), "merchants", ["hashed_api_key"], unique=True)
    op.drop_constraint(op.f("skus_shopify_variant_id_key"), "skus", type_="unique")
    op.drop_index(op.f("ix_skus_shopify_variant_id"), table_name="skus")
    op.create_index(op.f("ix_skus_shopify_variant_id"), "skus", ["shopify_variant_id"], unique=True)
    op.alter_column(
        "webhook_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "webhook_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_skus_shopify_variant_id"), table_name="skus")
    op.create_index(op.f("ix_skus_shopify_variant_id"), "skus", ["shopify_variant_id"], unique=False)
    op.create_unique_constraint(
        op.f("skus_shopify_variant_id_key"), "skus", ["shopify_variant_id"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_merchants_hashed_api_key"), table_name="merchants")
    op.create_index(op.f("ix_merchants_hashed_api_key"), "merchants", ["hashed_api_key"], unique=False)
    op.create_unique_constraint(
        op.f("merchants_hashed_api_key_key"), "merchants", ["hashed_api_key"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "llm_usage",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "idempotency_keys",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "idempotency_keys",
        "response_json",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
